### ISSUE TITLE
Naming convention of DTOs

### ISSUE THREAD

**Issue by Nictheboy** [SageSeekerSociety/cheese-backend#142]
We need to unify different conventions of DTO, especially response DTO.

We have three types of naming conventions of response DTO:

```
XxxResponseDto
XxxRespondDto
XxxDto
```

Whatever can be used, but only one should be used.

**Comment by andylizf** [comment]
There are three types of common DTOs:
- XDto, mapped from X entity, or to be reused
- XRequestDto, to be extracted from request body/query
- XResponseDto, to be returned **directly** as a response
