### ISSUE TITLE
Enhancement: Standardize Configuration and Project Structure

### ISSUE THREAD

**Issue by andylizf** [SageSeekerSociety/cheese-backend#23]
## Description
Currently, our SQL settings are hardcoded within `app.module.ts`, which limits the flexibility and clarity of our configuration, especially during testing. To improve maintainability and project structure, the following enhancements are proposed:

## Proposed Enhancements

1. **Separate SQL Configuration**:
   - Extract SQL configuration from `app.module.ts` into a dedicated configuration file, `ormconfig.ts`. This will allow for clearer and more centralized management of our ORM configuration.

2. **Rename `.secret` to `.config`**:
   - Rename the `.secret` folder to `.config` to better reflect its purpose and content. This folder will store configuration files, including `ormconfig.ts`, ensuring a more intuitive and standardized project structure.

3. **Enable Dynamic Logging Configuration for Testing**:
   - Implement a script or mechanism in GitHub Actions that enables SQL logging before tests are executed. This will provide valuable insights during testing without manually altering the configuration files.

4. **Standardize Configuration Files**:
   - Establish clear guidelines and standardize the relationship and configuration for `.eslintrc.json`, `.prettierrc`, and `.vscode` folders. This will ensure consistency and clarity in coding standards and editor configurations across the project.

## Benefits

- **Improved Clarity**: Centralizing and standardizing configuration files will make it easier for new contributors to understand the project structure and settings.
- **Enhanced Flexibility**: Separating the SQL logging configuration allows for more flexible enabling or disabling of logs, especially useful during different stages of development and testing.
- **Consistency in Code Quality**: Standardizing the configurations for ESLint, Prettier, and VSCode will promote consistency in code quality and formatting across the project.

I believe these enhancements will greatly contribute to the maintainability and clarity of the project.

**Comment by Nictheboy** [comment]
good idea
