### ISSUE TITLE
Enhance CI/CD Workflow with Docker Integration

### ISSUE THREAD

**Issue by andylizf** [SageSeekerSociety/cheese-backend#41]
It's suggested to enhance the GitHub Actions workflow by directly utilizing Docker for testing, and to streamline the Docker image release process by automatically publishing images to GitHub Container Registry (GHCR) upon pushes to the `main` branch. This approach aims to simplify and automate the release and Docker image publishing process.

Reference for automating tag creation, release, and Docker image publishing with GitHub Actions: [Automating tag creation, release, and Docker image publishing with GitHub Actions](https://dev.to/natilou/automating-tag-creation-release-and-docker-image-publishing-with-github-actions-49jg)

Considerations:
- Trigger a release and build an image upon pushing to `main`, avoiding separate release branches or manual release triggers.
- Use GHCR instead of DockerHub for hosting both `dev` and `main` versions of the Docker images, leveraging GitHub's integrated container service for streamlined operations.
- Investigate the possibility of building and tagging `dev` containers alongside the main releases, ensuring both development and production environments are up-to-date.

This enhancement could significantly improve the development and deployment efficiency by leveraging GitHub Actions and GHCR's capabilities.

**Comment by andylizf** [comment]
Please follow the changes on dev, adopt prisma and migrate to postgres. See https://github.com/notiz-dev/nestjs-prisma-starter.

**Comment by corporal9736** [comment]
done with [pr#53](https://github.com/SageSeekerSociety/cheese-backend/pull/53)
